
-module(rss).
-export([wanted/0]).

wanted() -> {{
  feed,
  undefined,
  undefined,
  undefined,
  <<"en-us">>,
  <<"http://liftoff.msfc.nasa.gov/">>,
  undefined,
  <<"Liftoff to Space Exploration.">>,
  <<"Liftoff News">>,
  <<"Tue, 10 Jun 2003 04:00:00 GMT">>,
  <<"http://liftoff.msfc.nasa.gov/">>}, [
{
  entry,
  undefined,
  [<<"second category">>,<<"first category">>],
  undefined,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/2003/06/03.html#item573">>,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/news/2003/news-starcity.asp">>,
  undefined,
  <<"How do Americans get ready to work with Russians aboard the International Space Station? They take a crash course in culture, language and protocol at Russia's <a href=\"http://howe.iki.rssi.ru/GCTC/gctc_e.htm\">Star City</a>.">>,
  <<"Star City">>,
  <<"Tue, 03 Jun 2003 09:39:21 GMT">>},
{
  entry,
  undefined,
  [<<"example category">>],
  undefined,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/2003/05/30.html#item572">>,
  undefined,
  undefined,
  undefined,
  <<"Sky watchers in Europe, Asia, and parts of Alaska and Canada will experience a <a href=\"http://science.nasa.gov/headlines/y2003/30may_solareclipse.htm\">partial eclipse of the Sun</a> on Saturday, May 31st.">>,
  undefined,
  <<"Fri, 30 May 2003 11:06:42 GMT">>},
{
  entry,
  undefined,
  [<<"example category">>],
  undefined,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/2003/05/27.html#item571">>,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/news/2003/news-VASIMR.asp">>,
  undefined,
  <<"Before man travels to Mars, NASA hopes to design new engines that will let us fly through the Solar System more quickly.  The proposed VASIMR engine would do that.">>,
  <<"The Engine That Does More">>,
  <<"Tue, 27 May 2003 08:37:32 GMT">>},
{
  entry,
  undefined,
  undefined,
  undefined,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/2003/05/20.html#item570">>,
  undefined,
  <<"http://liftoff.msfc.nasa.gov/news/2003/news-laundry.asp">>,
  undefined,
  <<"Compared to earlier spacecraft, the International Space Station has many luxuries, but laundry facilities are not one of them.  Instead, astronauts have other options.">>,
  <<"Astronauts' Dirty Laundry">>,
  <<"Tue, 20 May 2003 08:56:02 GMT">>}
]}.
